### ISSUE TITLE
Trouble step 3: saving photo

### ISSUE THREAD

**Issue by aclimarin** [ionic-team/photo-gallery-capacitor-react#10]
I'm learning ionic+react by **_ionicframework.com/docs/react_** and following the steps on Your First Ionic App. After the implementation, it's supose to save the photos, but this is not happening and that's no error on my web console. Can someone help me with this?

My code:
https://github.com/aclimarin/photo-galery

**Comment by aaronksaunders** [comment]
you are not saving the photos to local storage... you are only saving them to the current component state - added information to your repo

**Comment by jcesarmobile** [comment]
explained on https://github.com/aclimarin/photo-galery/issues/1, thanks aaronksaunders, closing
