### ISSUE TITLE
bug: css style seems broken on v3

### ISSUE THREAD

**Issue by jonz94** [ionic-team/photo-gallery-capacitor-react#36]
### Version

https://github.com/ionic-team/tutorial-photo-gallery-react/releases/tag/v3.0

### Current Behavior

When running dev server via `npm run start` command, the css style seems broken:

<img width="525" alt="Screenshot 2023-01-09 at 07 21 52" src="https://user-images.githubusercontent.com/16042676/211224511-616d2128-9da3-4df9-bc0a-798c553324fe.png">

### Expected Behavior

The page should be look like:

<img width="525" alt="Screenshot 2023-01-09 at 07 33 04" src="https://user-images.githubusercontent.com/16042676/211224535-a9a1bc80-75df-4e67-89ab-6adcecf4e7e0.png">

### Steps to Reproduce

1. `git clone https://github.com/ionic-team/tutorial-photo-gallery-react.git`
2. `cd tutorial-photo-gallery-react`
3. `npm ci`
4. `npm run start`
5. open google chrome and go to `http://localhost:3000`

**Comment by jonz94** [comment]
The root cause of this issue is seems to be the `setupIonicReact()` function call is missing.

Ref: https://github.com/ionic-team/starters/blob/3d2e5850079c1a99c85a31de5a5d8ebe43b2789f/react/official/tabs/src/App.tsx#L37

After adding `setupIonicReact()` in `src/App.tsx` file, the css style works as expected.

```diff
/* Global CSS */
import './global.css';

+setupIonicReact();

const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <IonTabs>
        <IonRouterOutlet>
          <Route path="/tab1" component={Tab1} exact={true} />
          <Route path="/tab2" component={Tab2} exact={true} />
          <Route path="/tab2/details" component={Details} />
          <Route path="/tab3" component={Tab3} />
          <Route path="/" render={() => <Redirect to="/tab1" />} exact={true} />
        </IonRouterOutlet>
        <IonTabBar slot="bottom">
          <IonTabButton tab="tab1" href="/tab1">
            <IonIcon icon={triangle} />
            <IonLabel>Tab One</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab2" href="/tab2">
            <IonIcon icon={images} />
            <IonLabel>Photos</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab3" href="/tab3">
            <IonIcon icon={square} />
            <IonLabel>Tab Three</IonLabel>
          </IonTabButton>
        </IonTabBar>
      </IonTabs>
    </IonReactRouter>
  </IonApp>
);

export default App;
```

**Comment by billy1624** [comment]
Just bumped into this issue. Thanks for the help!! @jonz94
