### ISSUE TITLE
Error: Loading module ... disallowed MIME type ("").

### ISSUE THREAD

**Issue by drewmo** [ionic-team/photo-gallery-capacitor-react#39]
In case anyone experiences the issue on page two of trying to capture a photo after first setting up the `usePhotoGallery()` hook and clicking the photo button for the first time. You may see the following in your console related to loading the pwa-camera-modal:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/7915652/232880362-cd0387ae-1108-406a-b553-d2491de42e1a.png">

The way to resolve this issue is to go into your `vite.config.ts` and remove the section for the test and replace it with this: 
```TS

//Remove:
test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.ts',
  }

//Replace with:
optimizeDeps: {
    exclude: ['@ionic/pwa-elements/loader']
  }
```

Your config file should now look like this:
```TS
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  optimizeDeps: {
    exclude: ['@ionic/pwa-elements/loader']
  }
})

```

This is a known issue in vite: https://github.com/vitejs/vite/issues/12434
You may need to delete your node_modules folder and install again.

**Comment by jcesarmobile** [comment]
this was fixed in pwa-elements
