### ISSUE TITLE
Bug on iOS replaces existing photos in gallery

### ISSUE THREAD

**Issue by lucnat** [ionic-team/photo-gallery-capacitor-react#8]
When running this on iOS, the gallery does not work reliably. If you save a couple of photos, close the app, restart it and add another photo, then some of the existing ones are replaced by the new ones. How come?

**Comment by dotNetkow** [comment]
I just retested the app on iOS 14 with an iPhone X and I couldn't reproduce. Can you tell me more details about how you're running the app, and what hardware you have etc? thanks.

**Comment by lucnat** [comment]
Hello. Indeed, I tried reproducing as well and wasnt able to either. I'll close this
